### ISSUE TITLE
test `neo init` example with travis

### ISSUE THREAD

**Issue by garbas** [taskcluster/neo#11]

**Comment by eliperelman** [comment]
This exits in https://github.com/eliperelman/neo-example but it can't be tested until 1.0.0 is actually published.

**Comment by garbas** [comment]
couldn't we do

```
% npm install
% mkdir example && cd example
% neo init
% neo test && neo build
```

that would test that ``neo init`` example is building and tests passing, wouldn't it?

**Comment by eliperelman** [comment]
Ooo good idea. I'll see what I can do.
