### ISSUE TITLE
port option still required 

### ISSUE THREAD

**Issue by garbas** [taskcluster/neo#16]
![2016-05-26-151617_843x395_scrot](https://cloud.githubusercontent.com/assets/20208/15575772/e65144c4-2354-11e6-9a17-4807cfa7e781.png)

also it would be nice to just display the error (in red)  without all those traceback.

**Comment by eliperelman** [comment]
@garbas can you check the vorpal version you have locally? I changed it to an earlier version, and it might not have been overwritten when you updated. That error is being thrown by karma, not vorpal, which leads me to believe vorpal did nothing about the port.

**Comment by garbas** [comment]
@eliperelman tnx it was my fault when i was merging my changes on top of yours yesterday. fixed [here](https://github.com/taskcluster/neo/commit/9dc5ab55ddced1890030fdb978d1a9e0ca186fd5).

but i'm still getting above error

**Comment by eliperelman** [comment]
Fixed.
